# AEM Sample Application

inherits:
- role: aem-cms

variants:
- variant: aem-author
- variant: aem-publish

templateDir: adaptto-provisionaem-aem-cms

files:

# Hotfixes/Service packs
#- url: mvn:de.provision.aem.hotfix.63/AEM-CFP-6.3.0.2/2.0.0/zip
#  dir: packages

# AEM Core WCM Components
- url: mvn:com.adobe.cq/core.wcm.components.all//zip
  dir: packages

# ACS AEM Commons
- url: mvn:com.adobe.acs/acs-aem-commons-content//zip/min
  dir: packages

# AEM OSGi System Configuration
- file: adaptto-provisionaem-aem-cms-config.provisioning
  dir: packages
  template: adaptto-provisionaem-aem-cms-config.provisioning.hbs
  postProcessors:
  - aem-contentpackage-osgiconfig
  postProcessorOptions:
    contentPackage:
      name: adaptto-provisionaem-aem-cms-config
      rootPath: /apps/adaptto-provisionaem-aem-cms-config/config
      filters:
      - filter: /apps/adaptto-provisionaem-aem-cms-config

# Application package
- url: mvn:org.adaptto.provisionaem/org.adaptto.provisionaem.complete//zip
  dir: packages

# Application sample content package
- url: mvn:org.adaptto.provisionaem/org.adaptto.provisionaem.sample-content//zip
  dir: packages
  condition: ${app.sampleContent}


# Defines configuration parameters and default values
config:
  contentPackage:
    group: adaptto-provisionaem
    version: "${version}"

  app:
    sampleContent: false
    developerMode: false
    errorPagePaths:
    - /content/adaptto-provisionaem-sample/:en/error
